version: '3.1' services:
    nginx:
      container_name: nginx
      image: nginx
      build:
        context: .
        dockerfile: .docker/nginx.dockerfile
      volumes:
        - ./dist/uSocial:/usr/share/nginx/html
      ports:
        - "80:80"