version: '3'

services:
  nodejs:
    build: .
    image: api:latest
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      PORT : 3000