-- MySQL Script generated by MySQL Workbench
-- vie 03 abr 2020 22:26:15 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `id_usuario` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `nickname` VARCHAR(50) NULL,
  `pass` VARCHAR(200) NULL,
  `urlimagen` VARCHAR(300) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PUBLICACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PUBLICACION` (
  `Id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `texto` VARCHAR(1000) NULL,
  `urlimagen` VARCHAR(300) NULL,
  `USUARIO_id_usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id_publicacion`),
  INDEX `fk_PUBLICACION_USUARIO_idx` (`USUARIO_id_usuario` ASC),
  CONSTRAINT `fk_PUBLICACION_USUARIO`
    FOREIGN KEY (`USUARIO_id_usuario`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
