-- MySQL Script generated by MySQL Workbench
-- mar 21 abr 2020 22:20:35 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `nickname` VARCHAR(50) NULL,
  `pass` VARCHAR(200) NULL,
  `urlimagen` VARCHAR(300) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicacion` (
  `id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NULL,
  `texto` VARCHAR(1000) NULL,
  `urlimagen` VARCHAR(300) NULL,
  `usuario_id_usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_publicacion`),
  INDEX `fk_publicacion_usuario_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_publicacion_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`amistad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`amistad` (
  `usuario_id_usuario` VARCHAR(50) NOT NULL,
  `usuario_id_usuario1` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`, `usuario_id_usuario1`),
  INDEX `fk_amistad_usuario2_idx` (`usuario_id_usuario1` ASC),
  CONSTRAINT `fk_amistad_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_amistad_usuario2`
    FOREIGN KEY (`usuario_id_usuario1`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chat` (
  `id_chat` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `texto` VARCHAR(500) NULL,
  `usuario_id_usuario_emisor` VARCHAR(50) NOT NULL,
  `usuario_id_usuarior_receptor` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_chat`),
  INDEX `fk_chat_usuario1_idx` (`usuario_id_usuario_emisor` ASC),
  INDEX `fk_chat_usuario2_idx` (`usuario_id_usuarior_receptor` ASC),
  CONSTRAINT `fk_chat_usuario1`
    FOREIGN KEY (`usuario_id_usuario_emisor`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_usuario2`
    FOREIGN KEY (`usuario_id_usuarior_receptor`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
